# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e042da85a522e1b0b06c505350c61143999f97e09bf9f1f0dcd80549a13d959be9f4c2e638be225e41dc6de1f28905401c770f6f552af9f43c418f65a47fa99c

test:
  secret_key_base: e57c2ea355392d2babcd705d740b094f3c43f208832772342eac28a53efcdb620335d77f8969ceb63d125a488aa9075e81f09f9919abb123e604dce8b8b51e78

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
